version: '3.5'

services:
  people_inbox:
    container_name: people_inbox
    build:
      context: .
      dockerfile: docker/Dockerfile-inbox
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - ./docker/people.toml:/opt/people/docker.people.toml

  people_grpc:
    container_name: people_grpc
    build:
      context: .
      dockerfile: docker/Dockerfile-grpc
    depends_on:
      postgres:
        condition: service_started
    ports:
      - 3001:3000
    volumes:
      - ./docker/people.toml:/opt/people/docker.people.toml

  people_grpc_proxy:
    container_name: people_grpc_proxy
    build:
      context: .
      dockerfile: docker/Dockerfile-grpc-proxy
    depends_on:
      people_grpc:
        condition: service_started
    ports:
      - 3002:3001
    volumes:
      - ./docker/people.toml:/opt/people/docker.people.toml

  # connect to postgres:
  #   connect to docker container
  #   switch to postgres user: su - postgres
  #   login as user "people": psql -U people
  postgres:
    container_name: postgres14
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    volumes:
      - postgres01:/var/lib/postgresql/data

  nats:
    container_name: nats
    image: nats:2.9.15
    volumes:
      - nats01:/data/jetstream
      - ./docker/nats.conf:/nats-server.conf
    ports:
      - 4223:4222

volumes:
  es01:
  postgres01:
  nats01:
