version: '3.5' 

# requirement: run "docker build -t person-service ." in order to create image person-service
services:
  person_service_inbox:
    image: ugentlib/person-service:latest
    container_name: person_service_inbox
    depends_on:
      postgres:
        condition: service_healthy
      # nats docker image has no shell to check health
      nats:
        condition: service_started
    volumes:
      - ./docker/.env:/opt/person-service/.env
    command: "/bin/sh -c \"cd /opt/person-service && ./person-service inbox listen\""

  person_service_grpc:
    container_name: person_service_grpc
    image: ugentlib/person-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - 3999
    ports:
      - 3999:3999
    volumes:
      - ./docker/.env:/opt/person-service/.env
    command: "/bin/sh -c \"cd /opt/person-service && ./person-service api start\""

  # connect to postgres:
  #   connect to docker container
  #   switch to postgres user: su - postgres
  #   login as user "people": psql -U people
  postgres:
    container_name: postgres14
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    volumes:
      - postgres01:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-U", "people"]
      interval: 5s
      timeout: 2s
      retries: 5

  nats:
    container_name: nats
    image: nats:2.9.15
    volumes:
      - nats01:/data/jetstream
      - ./docker/nats.conf:/nats-server.conf
    ports:
      - 4223:4222

volumes:
  postgres01:
  nats01:
