version: '3.5'

# requirement: run "docker build -t people-service ." in order to create image people-service
services:
  people_service_inbox_person:
    #image: ugentlib/people-service:latest
    image: people-service:latest
    container_name: people_service_inbox_person
    depends_on:
      postgres:
        condition: service_healthy
      # nats docker image has no shell to check health
      nats:
        condition: service_started
    volumes:
      - ./docker/.env:/opt/people-service/.env
    command: "/bin/sh -c \"cd /opt/people-service && ./people-service inbox listen person\""

  people_service_inbox_organization:
    #image: ugentlib/people-service:latest
    image: people-service:latest
    container_name: people_service_inbox_organization
    depends_on:
      postgres:
        condition: service_healthy
      # nats docker image has no shell to check health
      nats:
        condition: service_started
    volumes:
      - ./docker/.env:/opt/people-service/.env
    command: "/bin/sh -c \"cd /opt/people-service && ./people-service inbox listen organization\""

  people_service_server:
    container_name: people_service_server
    #image: ugentlib/people-service:latest
    image: people-service:latest
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - 3999
    ports:
      - 3999:3999
    volumes:
      - ./docker/.env:/opt/people-service/.env
    command: "/bin/sh -c \"cd /opt/people-service && ./people-service server start\""

  # connect to postgres:
  #   connect to docker container
  #   switch to postgres user: su - postgres
  #   login as user "people": psql -U people
  postgres:
    container_name: postgres14
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: people
      POSTGRES_USER: people
      POSTGRES_PASSWORD: people
    volumes:
      - postgres01:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "/usr/local/bin/pg_isready", "-U", "people"]
      interval: 5s
      timeout: 2s
      retries: 5

  nats:
    container_name: nats
    image: nats:2.9.15
    volumes:
      - nats01:/data/jetstream
      - ./docker/nats.conf:/nats-server.conf
    ports:
      - 4223:4222

volumes:
  postgres01:
  nats01:
