// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
	"github.com/ugent-library/people/ent/identifier"
)

// Identifier is the model entity for the Identifier schema.
type Identifier struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Identifier) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case identifier.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Identifier", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Identifier fields.
func (i *Identifier) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case identifier.FieldID:
			value, ok := values[j].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			i.ID = int(value.Int64)
		}
	}
	return nil
}

// Update returns a builder for updating this Identifier.
// Note that you need to call Identifier.Unwrap() before calling this method if this Identifier
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Identifier) Update() *IdentifierUpdateOne {
	return NewIdentifierClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Identifier entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Identifier) Unwrap() *Identifier {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Identifier is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Identifier) String() string {
	var builder strings.Builder
	builder.WriteString("Identifier(")
	builder.WriteString(fmt.Sprintf("id=%v", i.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Identifiers is a parsable slice of Identifier.
type Identifiers []*Identifier
