-- Create "organization" table
CREATE TABLE "organization" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamptz NOT NULL, "date_updated" timestamptz NOT NULL, "public_id" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'organization', "name_dut" character varying NULL, "name_eng" character varying NULL, "identifier" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "organization_public_id_key" to table: "organization"
CREATE UNIQUE INDEX "organization_public_id_key" ON "organization" ("public_id");
-- Create index "organization_type" to table: "organization"
CREATE INDEX "organization_type" ON "organization" ("type");
-- Create "organization_parent" table
CREATE TABLE "organization_parent" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamptz NOT NULL, "date_updated" timestamptz NOT NULL, "parent_organization_id" bigint NOT NULL, "organization_id" bigint NOT NULL, "from" timestamptz NOT NULL, "until" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create index "organizationparent_organization_id" to table: "organization_parent"
CREATE INDEX "organizationparent_organization_id" ON "organization_parent" ("organization_id");
-- Create index "organizationparent_parent_organization_id" to table: "organization_parent"
CREATE INDEX "organizationparent_parent_organization_id" ON "organization_parent" ("parent_organization_id");
-- Create "person" table
CREATE TABLE "person" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamptz NOT NULL, "date_updated" timestamptz NOT NULL, "public_id" character varying NOT NULL, "active" boolean NOT NULL DEFAULT false, "birth_date" character varying NULL, "email" character varying NULL, "identifier" jsonb NULL, "given_name" character varying NULL, "name" character varying NULL, "family_name" character varying NULL, "job_category" jsonb NULL, "preferred_given_name" character varying NULL, "preferred_family_name" character varying NULL, "honorific_prefix" character varying NULL, "role" jsonb NULL, "settings" jsonb NULL, "object_class" jsonb NULL, "expiration_date" character varying NULL, "token" jsonb NULL, PRIMARY KEY ("id"));
-- Create index "person_active" to table: "person"
CREATE INDEX "person_active" ON "person" ("active");
-- Create index "person_email" to table: "person"
CREATE INDEX "person_email" ON "person" ("email");
-- Create index "person_family_name" to table: "person"
CREATE INDEX "person_family_name" ON "person" ("family_name");
-- Create index "person_given_name" to table: "person"
CREATE INDEX "person_given_name" ON "person" ("given_name");
-- Create index "person_name" to table: "person"
CREATE INDEX "person_name" ON "person" ("name");
-- Create index "person_public_id_key" to table: "person"
CREATE UNIQUE INDEX "person_public_id_key" ON "person" ("public_id");
-- Create "organization_person" table
CREATE TABLE "organization_person" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "date_created" timestamptz NOT NULL, "date_updated" timestamptz NOT NULL, "from" timestamptz NOT NULL, "until" timestamptz NOT NULL, "person_id" bigint NOT NULL, "organization_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "organization_person_organization_organizations" FOREIGN KEY ("organization_id") REFERENCES "organization" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "organization_person_person_people" FOREIGN KEY ("person_id") REFERENCES "person" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "organizationperson_organization_id" to table: "organization_person"
CREATE INDEX "organizationperson_organization_id" ON "organization_person" ("organization_id");
-- Create index "organizationperson_person_id" to table: "organization_person"
CREATE INDEX "organizationperson_person_id" ON "organization_person" ("person_id");
-- Create index "organizationperson_person_id_organization_id" to table: "organization_person"
CREATE UNIQUE INDEX "organizationperson_person_id_organization_id" ON "organization_person" ("person_id", "organization_id");
